### ISSUE TITLE
Pick a code standard and enforce it

### ISSUE THREAD

**Issue by samtarling** [GeneralNotability/spihelper#57]
(TNT again!)

Code standards are second only to the "vim vs emacs" debate.
That being said, we should pick a JavaScript code standard and use [ESlint](https://eslint.org/) rules to enforce it.

I would personally suggest the popular [Standard](https://standardjs.com/) (even if it doesn't allow terminating semi-colons). To head off the potential complaints, I'd refer you to https://standardjs.com/#i-disagree-with-rule-x-can-you-change-it

### Todo
- [x] Choose a code standard
- [x] Set up `package.json` with appropriate `devDependencies` for other contributors
- [x] Set up `.eslintrc.json` file and do first `eslint spihelper.js`
- [x] Fix the errors (`356 problems (356 errors, 0 warnings)` after a `eslint --fix spihelper.js`)
- [x] ???
- [x] Profit
